---
root: true

env:
  browser: true
  es6: true

plugins:
  - "react-hooks"
  - "@typescript-eslint"

extends:
  - "react-app"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/recommended-requiring-type-checking"

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  project: "tsconfig.json"
  sourceType: module
